//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    :: cus_marco :: DeriveMaybeLeftRightTreeModel,
)]
#[sea_orm(table_name = "header2_task_rel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub main_task_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub main_header_id: i64,
    pub created_at: i64,
    pub updated_at: i64,
    pub deleted_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
