//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod cus_data_dict;
pub mod foreign_user;
pub mod header2_task_rel;
pub mod organization;
pub mod user;
pub mod user_organization;
pub mod work_content;
pub mod work_header;
pub mod work_task;
