//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::cus_data_dict::Entity as CusDataDict;
pub use super::foreign_user::Entity as ForeignUser;
pub use super::header2_task_rel::Entity as Header2TaskRel;
pub use super::organization::Entity as Organization;
pub use super::user::Entity as User;
pub use super::user_organization::Entity as UserOrganization;
pub use super::work_content::Entity as WorkContent;
pub use super::work_header::Entity as WorkHeader;
pub use super::work_task::Entity as WorkTask;
