//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    :: cus_marco :: DeriveMaybeLeftRightTreeModel,
)]
#[sea_orm(table_name = "work_header")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub content_type_dc_id: i64,
    pub open_dc_id: i64,
    pub tag: i64,
    pub right: i64,
    pub organization_id: i64,
    pub left: i64,
    pub level: i64,
    pub creator: i64,
    pub editor: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cus_data_dict::Entity",
        from = "Column::ContentTypeDcId",
        to = "super::cus_data_dict::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CusDataDict2,
    #[sea_orm(
        belongs_to = "super::cus_data_dict::Entity",
        from = "Column::OpenDcId",
        to = "super::cus_data_dict::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CusDataDict1,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organization,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Creator",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Editor",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
    #[sea_orm(has_many = "super::work_content::Entity")]
    WorkContent,
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl Related<super::work_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkContent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
